<script setup lang="ts">
import type {
  AttributeObjectWithoutVariant,
} from "@/types/catalogueAttribute";

interface Props {
  fieldName: string
  attribute: AttributeObjectWithoutVariant
  isVariant?: boolean
}
const props = withDefaults(defineProps<Props>(), {
  isVariant: false,
})

const showLabelField = computed(() => ATTRIBUTES_WITH_LABEL_INPUT.includes(props.attribute.type))
const isReadonlyLabelField = computed(() => ATTRIBUTES_WITH_READONLY_LABEL.includes(props.attribute.type))

const attributeType = computed(() => props.isVariant ? "variant" : "property")

const labelFieldProps = computed(() => ({
  placeholder: isReadonlyLabelField.value
    ? `Label for this ${attributeType.value}`
    : `Enter the label for this ${attributeType.value}`,

  readonly: isReadonlyLabelField.value,

  description: isReadonlyLabelField.value
    ? "Label will be autogenerated"
    : undefined,
}))
</script>

<template>
  <FormFieldInput
    v-if="showLabelField"
    :name="`${fieldName}.label`"
    v-bind="labelFieldProps"
    class="gap-y-1.25 [&_input]:text-xs">
    <template #label>
      <FormLabel class="text-xs font-medium text-muted-foreground capitalize">
        {{ attributeType }} Label
      </FormLabel>
    </template>
  </FormFieldInput>
</template>
