import type { Metadata } from "next"
import { test } from "@turbo-mart/utils/index"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  test()

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
