# Auth APIs

openapi: 3.1.1
info:
  title: Auth API Documentation
  version: 1.0.0
paths:

  # Login API
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      description: Endpoint for users to enter credentials and login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address.
                password:
                  type: string
                  description: User's password.
      responses:
        "200":
          description: Successfully logged in and received authentication token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Boolean indicating whether the request was successful.
                  message:
                    type: string
                    description: Success message.
                    example: "Login successful"
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          id:
                            type: string
                            description: Unique user ID.
                          email:
                            type: string
                            description: User's email address.
                          name:
                            type: string
                            description: User's full name.
                          role:
                            type: string
                            description: User's role (e.g., "SUPER_ADMIN", "ADMIN").
                      token:
                        type: object
                        properties:
                          value:
                            type: string
                            description: Bearer token for the authenticated session.
                          expiresAt:
                            type: string
                            format: date-time
                            description: Expiration time of the token.
        "401":
          description: Invalid credentials (either email or password incorrect).
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                    description: Indicates the request failed.
                  message:
                    type: string
                    example: Invalid email or password
                    description: Error message.
        "422":
          description: Validation error (if request body is missing required fields).
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                    description: Indicates the request failed.
                  message:
                    type: string
                    example: Validation Error
                    description: Error message.
                  errors:
                    type: object
                    description: Validation error details for the fields.
                    properties:
                      email:
                        type: array
                        items:
                          type: string
                        example: ["Please enter your email"]
                        description: Validation errors for the email field.
                      password:
                        type: array
                        items:
                          type: string
                        example: ["Please enter your password"]
                        description: Validation errors for the password field.
        "500":
          $ref: "#/components/responses/InternalServerError"

  # Logout API
  /api/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      description: Endpoint for users to logout.
      responses:
        "200":
          description: Successfully logged out user and removed authentication token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Boolean indicating whether the request was successful.
                  message:
                    type: string
                    description: Success message.
                    example: "Logout successful"
        "401":
          $ref: "#/components/responses/UnauthorizedUser"
        "500":
          $ref: "#/components/responses/InternalServerError"