<script setup lang="ts">
import {
  AttributeType,
} from "@app/database/mongoose/enums/catalogue/attribute";
import type {
  AttributeObjectWithoutVariant,
} from "@/types/catalogueAttribute";
import {
  CatalogueProductFormAttributesValueText,
  CatalogueProductFormAttributesValueNumber,
  CatalogueProductFormAttributesValueBoolean,
  CatalogueProductFormAttributesValueSelect,
  CatalogueProductFormAttributesValueMultiSelect,
  CatalogueProductFormAttributesValueColor,
  CatalogueProductFormAttributesValueDate,
  CatalogueProductFormAttributesValueJson,
} from "#components"

interface Props {
  fieldBase: string
  attribute: AttributeObjectWithoutVariant
}
const props = defineProps<Props>()

const ATTRIBUTES_WITH_READONLY_LABEL: Array<AttributeType> = [
  AttributeType.DATE
]
const ATTRIBUTES_WITH_LABEL_INPUT: Array<AttributeType> = [
  AttributeType.NUMBER,
  AttributeType.COLOR,
  ...ATTRIBUTES_WITH_READONLY_LABEL,
] as const
const showLabelField = computed(() => ATTRIBUTES_WITH_LABEL_INPUT.includes(props.attribute.type))
const isReadonlyLabelField = computed(() => ATTRIBUTES_WITH_READONLY_LABEL.includes(props.attribute.type))

const VALUE_META_COMPONENT_MAP = {
  [AttributeType.TEXT]: CatalogueProductFormAttributesValueText,
  [AttributeType.NUMBER]: CatalogueProductFormAttributesValueNumber,
  [AttributeType.BOOLEAN]: CatalogueProductFormAttributesValueBoolean,
  [AttributeType.SELECT]: CatalogueProductFormAttributesValueSelect,
  [AttributeType.MULTI_SELECT]: CatalogueProductFormAttributesValueMultiSelect,
  [AttributeType.COLOR]: CatalogueProductFormAttributesValueColor,
  [AttributeType.DATE]: CatalogueProductFormAttributesValueDate,
  [AttributeType.JSON]: CatalogueProductFormAttributesValueJson,
} as const
const ValueMetaComponent = computed(() => VALUE_META_COMPONENT_MAP[props.attribute.type])

const labelFieldProps = computed(() => ({
  placeholder: isReadonlyLabelField.value
    ? "Label for this attribute"
    : "Enter the label for this attribute",

  readonly: isReadonlyLabelField.value,

  description: isReadonlyLabelField.value
    ? "Label will be autogenerated"
    : undefined,
}))

const {
  setFieldValue,
} = useForm()

function updateLabel(derivedLabel: string) {
  setFieldValue(`${props.fieldBase}.label`, derivedLabel)
}
</script>

<template>
  <div class="space-y-2">
    <!-- type based value and meta fields component -->
    <component
      :is="ValueMetaComponent"
      :name="`${fieldBase}.value`"
      :attribute
      @label-change="updateLabel" />

    <FormFieldInput
      v-if="showLabelField"
      :name="`${fieldBase}.label`"
      v-bind="labelFieldProps"
      class="gap-y-1.25 [&_input]:text-xs">
      <template #label>
        <FormLabel class="text-xs font-medium text-muted-foreground">
          Label
        </FormLabel>
      </template>
    </FormFieldInput>
  </div>
</template>
