<script setup lang="ts">
import type {
  AttributeObjectWithoutVariant,
} from "@/types/catalogueAttribute";

interface Props {
  labelName: string
  attribute: AttributeObjectWithoutVariant
}
const props = defineProps<Props>()

const showLabelField = computed(() => ATTRIBUTES_WITH_LABEL_INPUT.includes(props.attribute.type))
const isReadonlyLabelField = computed(() => ATTRIBUTES_WITH_READONLY_LABEL.includes(props.attribute.type))

const labelFieldProps = computed(() => ({
  placeholder: isReadonlyLabelField.value
    ? "Label for this attribute"
    : "Enter the label for this attribute",

  readonly: isReadonlyLabelField.value,

  description: isReadonlyLabelField.value
    ? "Label will be autogenerated"
    : undefined,
}))
</script>
<template>
  <FormFieldInput
    v-if="showLabelField"
    :name="labelName"
    v-bind="labelFieldProps"
    class="gap-y-1.25 [&_input]:text-xs">
    <template #label>
      <FormLabel class="text-xs font-medium text-muted-foreground">
        Label
      </FormLabel>
    </template>
  </FormFieldInput>
</template>